#!/bin/bash

# DNS Configuration Script
# This script configures systemd-resolved for optimized DNS performance

# ANSI color codes for better readability
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Display script banner
echo -e "${BLUE}=================================================${NC}"
echo -e "${BLUE}      DNS Configuration Utility v1.0             ${NC}"
echo -e "${BLUE}=================================================${NC}"

# Check if running with root privileges
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Error: This script requires root privileges.${NC}"
  echo -e "Please run with sudo: ${YELLOW}sudo $0${NC}"
  exit 1
fi

echo -e "\n${GREEN}Starting DNS configuration...${NC}"
#!/bin/bash

# Script to find and remove any DNS config files in /etc/systemd
# except the main config file /etc/systemd/resolved.conf

echo "Starting DNS configuration cleanup..."
echo "Keeping main config: /etc/systemd/resolved.conf"

# Find all files in /etc/systemd that contain 'resolved.conf' in the name
# but exclude the main config file
find /etc/systemd -type f -path "*/resolved.conf*" ! -path "/etc/systemd/resolved.conf" | while read -r file; do
    echo "Found extra DNS config: $file"
    echo "Removing: $file"
    rm -v "$file"
done

# Specifically look for the resolved.conf.d directory and handle its contents
if [ -d "/etc/systemd/resolved.conf.d" ]; then
    echo "Found resolved.conf.d directory with extra configs:"
    find /etc/systemd/resolved.conf.d -type f | while read -r file; do
        echo "Removing: $file"
        rm -v "$file"
    done
    
    # Check if directory is now empty and remove it if it is
    if [ -z "$(ls -A /etc/systemd/resolved.conf.d)" ]; then
        echo "Directory /etc/systemd/resolved.conf.d is now empty, removing it."
        rmdir -v /etc/systemd/resolved.conf.d
    fi
fi

echo "DNS configuration cleanup completed."
# Configure DNS settings
setup_dns() {
  echo -e "\n${YELLOW}Step 1: Preparing system files...${NC}"
  
  # Make resolv.conf writable if it's immutable
  echo "Checking resolv.conf attributes..."
  if lsattr /etc/resolv.conf 2>/dev/null | grep -q "i"; then
    echo "Removing immutable flag from /etc/resolv.conf"
    chattr -i /etc/resolv.conf
  fi

  # Backup existing resolv.conf if it's not a symlink
  if [ -f /etc/resolv.conf ] && [ ! -L /etc/resolv.conf ]; then
    resolv_backup="/etc/resolv.conf.bak.$(date +%F-%T)"
    echo "Backing up original /etc/resolv.conf to $resolv_backup"
    cp /etc/resolv.conf "$resolv_backup"
  fi

  # Backup existing resolved.conf (timestamped for safety)
  config_file="/etc/systemd/resolved.conf"
  backup_file="$config_file.bak.$(date +%F-%T)"
  
  if [ -f "$config_file" ]; then
    echo "Creating backup of existing configuration at $backup_file"
    cp "$config_file" "$backup_file"
  else
    echo "Warning: $config_file not found, creating new one"
  fi

  echo -e "\n${YELLOW}Step 2: Applying new DNS settings...${NC}"
  
  # Create a clean configuration
  cat > "$config_file" <<EOL
# systemd-resolved configuration
# Generated by DNS Configuration Utility on $(date)
[Resolve]
DNS=1.1.1.1 8.8.8.8
DNSStubListener=no
Cache=yes
CacheFromLocalhost=no
DNSSEC=no
DNSOverTLS=no
LLMNR=no
MulticastDNS=no
ReadEtcHosts=no
EOL

  echo "DNS settings applied to $config_file"

  # Update /etc/resolv.conf to point to systemd's resolver
  echo -e "\n${YELLOW}Step 3: Updating resolv.conf...${NC}"
  
  # Properly handle the existing resolv.conf
  if [ -L /etc/resolv.conf ]; then
    echo "Removing existing symbolic link /etc/resolv.conf"
    rm /etc/resolv.conf
  elif [ -f /etc/resolv.conf ]; then
    echo "Removing existing file /etc/resolv.conf"
    rm /etc/resolv.conf
  elif [ -e /etc/resolv.conf ]; then
    echo "Removing existing /etc/resolv.conf (unknown type)"
    rm -f /etc/resolv.conf
  fi
  
  # Create the new symlink
  ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
  echo "Created symlink: /etc/resolv.conf -> /run/systemd/resolve/resolv.conf"

  # Restart systemd-resolved to apply changes
  echo -e "\n${YELLOW}Step 4: Applying changes...${NC}"
  systemctl restart systemd-resolved
  
  # Verify the service is running
  if systemctl is-active --quiet systemd-resolved; then
    echo -e "${GREEN}systemd-resolved service restarted successfully${NC}"
  else
    echo -e "${RED}Warning: systemd-resolved service failed to restart${NC}"
    echo "Please check system logs for details"
  fi
}

# Display current DNS servers
show_current_dns() {
  echo -e "\n${YELLOW}Current DNS Configuration:${NC}"
  echo -e "${BLUE}---------------------------${NC}"
  
  if systemctl is-active --quiet systemd-resolved; then
    echo "systemd-resolved status:"
    resolvectl status | grep "DNS Server" || echo "No DNS servers found in resolvectl"
  else
    echo "systemd-resolved is not running"
  fi
  
  
  # Check if it's a symlink and show the target
  if [ -L /etc/resolv.conf ]; then
    echo -e "\nSymlink target: $(readlink -f /etc/resolv.conf)"
  fi
}

# Main execution
setup_dns
show_current_dns

echo -e "\n${GREEN}DNS Configuration Complete!${NC}"
echo -e "${BLUE}==================================================${NC}"
echo -e "DNS servers set to: Cloudflare (1.1.1.1, 8.8.8.8)"
echo -e "                    Google    (8.8.8.8, 8.8.4.4)"
echo -e "${BLUE}==================================================${NC}"
echo -e "You can test your DNS setup with: ${YELLOW}dig example.com${NC}"
echo -e "If you experience any issues, the backup is at: ${YELLOW}$backup_file${NC}\n"

echo -n "Do you want to also change DNS on netplan? (y/n): "
read -r answer

# Check if the answer starts with 'y' or 'Y'
if [[ $answer =~ ^[Yy] ]]; then
#!/bin/bash

# Improved script to configure Cloudflare DNS in Netplan
# Only modifies the 'addresses' list within existing 'nameservers' sections.
# Cloudflare DNS servers: 1.1.1.1 and 8.8.8.8

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root. Please use sudo."
    exit 1
fi

# Check if python3 and PyYAML are available
if ! command -v python3 &> /dev/null; then
    echo "Error: python3 is not installed. Please install it (e.g., sudo apt update && sudo apt install python3)."
    exit 1
fi
if ! python3 -c "import yaml" &> /dev/null; then
    echo "Error: PyYAML module for Python3 is not installed. Please install it (e.g., sudo apt update && sudo apt install python3-yaml)."
    exit 1
fi


# Define the desired comment header
COMMENT_HEADER="# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}"

# Define the Netplan config file path
NETPLAN_DIR="/etc/netplan"
NETPLAN_CONFIG=""
BACKUP_FILE="" # Initialize backup file variable

# Find the existing Netplan configuration file
# Prefer files that don't look like backups
# Find Netplan config files using find command
# Get all valid Netplan config files
mapfile -d '' netplan_configs < <(find "$NETPLAN_DIR" -maxdepth 1 -type f \( -name '*.yaml' ! -name '*.bak' ! -name '*.old' ! -name '*.orig' \) -print0 2>/dev/null)

# Process files
if (( ${#netplan_configs[@]} > 0 )); then
    echo "Found Netplan configurations:"
    printf '  - %s\n' "${netplan_configs[@]}"
    NETPLAN_CONFIG="${netplan_configs[0]}" # Select first file
else
    echo "No Netplan configurations found"
fi

if [ -z "$NETPLAN_CONFIG" ]; then
    echo "No existing Netplan configuration found in $NETPLAN_DIR"
    echo "Creating a new configuration file: 01-netcfg.yaml"
    NETPLAN_CONFIG="$NETPLAN_DIR/01-netcfg.yaml"

    # Create a basic Netplan config with Cloudflare DNS and desired format
    # Note: This assumes eth0 with DHCP, modify if your default is different
    # No need to apply/verify yet, let the rest of the script handle it if needed
else
    echo "Processing existing configuration: $NETPLAN_CONFIG"

    # Create a backup of the current configuration
    BACKUP_FILE="$NETPLAN_CONFIG.bak.$(date +%Y%m%d%H%M%S)"
    cp "$NETPLAN_CONFIG" "$BACKUP_FILE"
    echo "Created backup at $BACKUP_FILE"

    # Use Python to parse, modify (only DNS addresses), and format the YAML
    # Python script will print the modified YAML to stdout
    MODIFIED_YAML=$(python3 -c "
import yaml
import sys
import io

# Load the YAML file
try:
    with open('$NETPLAN_CONFIG', 'r') as f:
        config = yaml.safe_load(f)
except yaml.YAMLError as e:
    print(f'Error parsing YAML: {e}', file=sys.stderr)
    sys.exit(1)
except FileNotFoundError:
    print(f'Error: File not found: $NETPLAN_CONFIG', file=sys.stderr)
    sys.exit(1)


# Function to modify DNS recursively
def set_cloudflare_dns_addresses(conf):
    modified = False
    if isinstance(conf, dict):
        # Iterate through top-level keys (like ethernets, wifis, etc.)
        for key, value in conf.items():
            # Check if this value contains interface configurations
            if key in ('ethernets', 'wifis', 'bridges', 'bonds', 'vlans') and isinstance(value, dict):
                for iface, iface_config in value.items():
                    # Check if it's a dictionary (representing an interface config)
                    if isinstance(iface_config, dict):
                        # --- Modification Start ---
                        # Check if 'nameservers' exists and is a dictionary
                        if 'nameservers' in iface_config and isinstance(iface_config['nameservers'], dict):
                            # Only update the 'addresses' key within the existing 'nameservers' dict
                            iface_config['nameservers']['addresses'] = ['1.1.1.1', '8.8.8.8']
                            modified = True
                        # --- Modification End ---
                        # If 'nameservers' doesn't exist or isn't a dict, we don't touch it.
            # Recursively process nested structures if needed (less common in flat netplan)
            # elif isinstance(value, dict):
            #     if set_cloudflare_dns_addresses(value): # Call the renamed function
            #         modified = True
    return modified

# Process the config
if config and 'network' in config:
    network_section = config.get('network', {})
    if isinstance(network_section, dict):
        # Call the updated function
        if set_cloudflare_dns_addresses(network_section):
            # Dump the updated config to a string with desired indentation
            try:
                output = io.StringIO()
                yaml.dump(config, output, default_flow_style=False, indent=4, sort_keys=False, width=float('inf'))
                print(output.getvalue()) # Print YAML to stdout
                sys.exit(0) # Success
            except Exception as e:
                 print(f'Error dumping YAML: {e}', file=sys.stderr)
                 sys.exit(1)
        else:
            # This case means no existing 'nameservers' sections were found/modified
            print('Warning: No existing "nameservers" sections found to modify in the config.', file=sys.stderr)
            # Exit non-zero because the script's primary goal wasn't met.
            # If you want the script to succeed even if no changes were made, exit 0 here.
            sys.exit(1)
    elif not isinstance(network_section, dict):
        print(f'Error: Expected "network" section to be a dictionary, but got {type(network_section)}', file=sys.stderr)
        sys.exit(1)
else:
    print('Invalid or empty network configuration format (missing "network" key?).', file=sys.stderr)
    sys.exit(1)
")

    # Check if Python script succeeded
    PYTHON_EXIT_CODE=$?
    if [ $PYTHON_EXIT_CODE -ne 0 ]; then
        # Check if the exit code is 1, which we now use for "no modification needed" warning
        if [ $PYTHON_EXIT_CODE -eq 1 ]; then
             echo "Python script indicated no modifications were needed (no existing 'nameservers' found)."
             # Decide if this is an error or not. For now, we'll just exit cleanly.
             # Remove the backup file as no changes were made.
             rm -f "$BACKUP_FILE"
             echo "No changes applied to $NETPLAN_CONFIG."
             exit 0 # Exit cleanly as no error occurred, just nothing to do.
        else
            # Other Python errors
            echo "Failed to process configuration using Python (Exit code: $PYTHON_EXIT_CODE)."
            echo "Check Python error messages above."
            echo "Restoring backup."
            if [ -f "$BACKUP_FILE" ]; then
                 sudo cp "$BACKUP_FILE" "$NETPLAN_CONFIG"
            else
                 echo "Error: Backup file $BACKUP_FILE not found!"
            fi
            exit 1 # Exit with error
        fi
    elif [ -z "$MODIFIED_YAML" ]; then
         # This case should be less likely now with the specific exit codes
         echo "Python script produced empty output unexpectedly. Aborting."
         echo "Restoring backup."
         if [ -f "$BACKUP_FILE" ]; then
             sudo cp "$BACKUP_FILE" "$NETPLAN_CONFIG"
         else
             echo "Error: Backup file $BACKUP_FILE not found!"
         fi
         exit 1
    fi

    # --- If Python succeeded (exit code 0) and produced output ---

    # Write the header and the modified YAML back to the file
    echo "Writing updated configuration to $NETPLAN_CONFIG..."
    TMP_FILE=$(mktemp)
    echo "$COMMENT_HEADER" > "$TMP_FILE"
    echo "$MODIFIED_YAML" >> "$TMP_FILE"

    # Atomically replace the original file
    if sudo mv "$TMP_FILE" "$NETPLAN_CONFIG"; then
        sudo chmod 644 "$NETPLAN_CONFIG"
        echo "Updated Netplan configuration content written."
    else
        echo "Error: Failed to move temporary file to $NETPLAN_CONFIG."
        rm -f "$TMP_FILE"
        echo "Restoring backup."
        if [ -f "$BACKUP_FILE" ]; then
            sudo cp "$BACKUP_FILE" "$NETPLAN_CONFIG"
        else
            echo "Error: Backup file $BACKUP_FILE not found!"
        fi
        exit 1
    fi

fi # End of handling existing vs new file

# --- Common steps only if changes were potentially made ---

# Check if MODIFIED_YAML is non-empty (meaning we processed an existing file and made changes)
# Or if NETPLAN_CONFIG was just created (backup file is empty)
if [ -n "$MODIFIED_YAML" ] || [ -z "$BACKUP_FILE" ]; then

    # Validate the configuration before applying
    echo "Validating Netplan configuration..."
    if ! sudo netplan try --timeout 30; then
        echo "-------------------------------------------"
        echo "ERROR: Netplan validation failed ('netplan try')."
        echo "The configuration in $NETPLAN_CONFIG is invalid."
        if [ -n "$BACKUP_FILE" ] && [ -f "$BACKUP_FILE" ]; then
           echo "Restoring backup from $BACKUP_FILE..."
           sudo cp "$BACKUP_FILE" "$NETPLAN_CONFIG"
           echo "Applying the restored configuration..."
           if sudo netplan apply; then
               echo "Successfully restored and applied backup."
           else
               echo "ERROR applying the restored backup configuration. Manual intervention required."
           fi
        else
           echo "No backup file available to restore (or new file was created). Manual intervention required."
           echo "The invalid configuration is in $NETPLAN_CONFIG."
        fi
        echo "-------------------------------------------"
        exit 1
    fi

    # If validation succeeded
    echo "Netplan configuration appears valid."
    echo "Applying final Netplan configuration..."
    if ! sudo netplan apply > /dev/null 2>&1; then
        echo "-------------------------------------------"
        echo "ERROR: Failed to apply Netplan configuration ('netplan apply')."
        if [ -n "$BACKUP_FILE" ] && [ -f "$BACKUP_FILE" ]; then
            echo "Attempting to restore backup from $BACKUP_FILE..."
            sudo cp "$BACKUP_FILE" "$NETPLAN_CONFIG"
            echo "Applying the restored configuration..."
            if sudo netplan apply; then
               echo "Successfully restored and applied backup."
            else
               echo "ERROR applying the restored backup configuration. Manual intervention required."
            fi
        else
            echo "No backup file available to restore. Manual intervention required."
        fi
        echo "-------------------------------------------"
        exit 1
    fi

    # If apply succeeded
    echo "Cloudflare DNS configuration has been successfully applied!"
    echo "Your system should now be using Cloudflare DNS (1.1.1.1 and 8.8.8.8) where applicable."

    # Verify DNS servers
    echo "Verifying DNS configuration..."
    sleep 2
    if command -v resolvectl &> /dev/null; then
        resolvectl status | grep "DNS Servers"
    elif command -v systemd-resolve &> /dev/null; then
        systemd-resolve --status | grep "DNS Servers"
    else
        echo "Could not find resolvectl or systemd-resolve to verify DNS settings."
    fi

else
    # This branch is reached if we processed an existing file but Python exited with code 1 (no changes needed)
    echo "No changes were made to the configuration file."
fi

exit 0
fi
