#!/bin/bash

# DNS Configuration Script
# This script configures systemd-resolved for optimized DNS performance

# ANSI color codes for better readability
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Display script banner
echo -e "${BLUE}=================================================${NC}"
echo -e "${BLUE}      DNS Configuration Utility v1.0             ${NC}"
echo -e "${BLUE}=================================================${NC}"

# Check if running with root privileges
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Error: This script requires root privileges.${NC}"
  echo -e "Please run with sudo: ${YELLOW}sudo $0${NC}"
  exit 1
fi

echo -e "\n${GREEN}Starting DNS configuration...${NC}"

# Configure DNS settings
setup_dns() {
  echo -e "\n${YELLOW}Step 1: Preparing system files...${NC}"
  
  # Make resolv.conf writable if it's immutable
  echo "Checking resolv.conf attributes..."
  if lsattr /etc/resolv.conf 2>/dev/null | grep -q "i"; then
    echo "Removing immutable flag from /etc/resolv.conf"
    chattr -i /etc/resolv.conf
  fi

  # Backup existing resolv.conf if it's not a symlink
  if [ -f /etc/resolv.conf ] && [ ! -L /etc/resolv.conf ]; then
    resolv_backup="/etc/resolv.conf.bak.$(date +%F-%T)"
    echo "Backing up original /etc/resolv.conf to $resolv_backup"
    cp /etc/resolv.conf "$resolv_backup"
  fi

  # Backup existing resolved.conf (timestamped for safety)
  config_file="/etc/systemd/resolved.conf"
  backup_file="$config_file.bak.$(date +%F-%T)"
  
  if [ -f "$config_file" ]; then
    echo "Creating backup of existing configuration at $backup_file"
    cp "$config_file" "$backup_file"
  else
    echo "Warning: $config_file not found, creating new one"
  fi

  echo -e "\n${YELLOW}Step 2: Applying new DNS settings...${NC}"
  
  # Create a clean configuration
  cat > "$config_file" <<EOL
# systemd-resolved configuration
# Generated by DNS Configuration Utility on $(date)
[Resolve]
DNS=1.1.1.1 8.8.8.8
DNSStubListener=no
Cache=yes
CacheFromLocalhost=no
DNSSEC=no
DNSOverTLS=no
LLMNR=no
MulticastDNS=no
ReadEtcHosts=no
EOL

  echo "DNS settings applied to $config_file"

  # Update /etc/resolv.conf to point to systemd's resolver
  echo -e "\n${YELLOW}Step 3: Updating resolv.conf...${NC}"
  
  # Properly handle the existing resolv.conf
  if [ -L /etc/resolv.conf ]; then
    echo "Removing existing symbolic link /etc/resolv.conf"
    rm /etc/resolv.conf
  elif [ -f /etc/resolv.conf ]; then
    echo "Removing existing file /etc/resolv.conf"
    rm /etc/resolv.conf
  elif [ -e /etc/resolv.conf ]; then
    echo "Removing existing /etc/resolv.conf (unknown type)"
    rm -f /etc/resolv.conf
  fi
  
  # Create the new symlink
  ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
  echo "Created symlink: /etc/resolv.conf -> /run/systemd/resolve/resolv.conf"

  # Restart systemd-resolved to apply changes
  echo -e "\n${YELLOW}Step 4: Applying changes...${NC}"
  systemctl restart systemd-resolved
  
  # Verify the service is running
  if systemctl is-active --quiet systemd-resolved; then
    echo -e "${GREEN}systemd-resolved service restarted successfully${NC}"
  else
    echo -e "${RED}Warning: systemd-resolved service failed to restart${NC}"
    echo "Please check system logs for details"
  fi
}

# Display current DNS servers
show_current_dns() {
  echo -e "\n${YELLOW}Current DNS Configuration:${NC}"
  echo -e "${BLUE}---------------------------${NC}"
  
  if systemctl is-active --quiet systemd-resolved; then
    echo "systemd-resolved status:"
    resolvectl status | grep "DNS Server" || echo "No DNS servers found in resolvectl"
  else
    echo "systemd-resolved is not running"
  fi
  
  
  # Check if it's a symlink and show the target
  if [ -L /etc/resolv.conf ]; then
    echo -e "\nSymlink target: $(readlink -f /etc/resolv.conf)"
  fi
}

# Main execution
setup_dns
show_current_dns

echo -e "\n${GREEN}DNS Configuration Complete!${NC}"
echo -e "${BLUE}==================================================${NC}"
echo -e "DNS servers set to: Cloudflare (1.1.1.1, 1.0.0.1)"
echo -e "                    Google    (8.8.8.8, 8.8.4.4)"
echo -e "${BLUE}==================================================${NC}"
echo -e "You can test your DNS setup with: ${YELLOW}dig example.com${NC}"
echo -e "If you experience any issues, the backup is at: ${YELLOW}$backup_file${NC}\n"
